os: linux

dist: bionic

language: shell

git:
  depth: 1

before_script:
  - export -f travis_cmd
  - export -f travis_fold
  - export -f travis_nanoseconds
  - export -f travis_time_finish
  - export -f travis_time_start
  - >
    travis_fold_cmd() {
      travis_fold start "${1}"
      travis_cmd "${2}"  --echo --timing
      travis_fold end "${1}"
    }
  - export -f travis_fold_cmd

script:
  - travis_cmd ls\ -lR\ $HOME --echo --timing
  - travis_fold start ls
  - travis_cmd ls\ -l\ * --echo --timing
  - travis_fold end ls
  - |
    travis_fold start ls
    travis_cmd ls\ -l\ * --echo --timing
    travis_fold end ls
  - travis_fold_cmd ls ls\ -l\ *
